default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    # Display on macOS
    notification(subtitle: "Finished Test", message: "")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
#     upload_to_play_store
  end

    desc "Submit a new Beta Build to Firebase App Distribution"
    lane :distribute do
      build_android_app(task: 'assemble', build_type: 'Debug')

      release = firebase_app_distribution(
          app: "1:1096732870156:android:9d2cd027ad33a14b785029",
          testers: "mason.wu@tpisoftware.com",
          release_notes: "Lots of amazing new features to test out!"
      )
    end
end
